### ISSUE TITLE
Phase 3

### ISSUE THREAD

**Issue by cjavdev** [erichsu7/SelFeed#2]
is not really a feature, but building blocks of features you should use for every step. Make sure you have a json api and backbone models built out at every phase for that specific feature.

**Comment by erichsu7** [comment]
I've update the title of this phase. Really all I'm doing here is displaying uploaded pictures and displaying them on the user show page, which will require converting the User show Rails view to a Backbone one. Also, I'm going to try to implement infinite scrolling.
